// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SharePointAgent.Persistence;

#nullable disable

namespace SharePointAgent.Persistence.Migrations
{
    [DbContext(typeof(SharePointIndexDbContext))]
    partial class SharePointIndexDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SharePointAgent.Persistence.AgentDefinitionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AgentDefinitions", (string)null);
                });

            modelBuilder.Entity("SharePointAgent.Persistence.ChatConversationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AgentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<long>("InputTokenCount")
                        .HasColumnType("bigint");

                    b.Property<string>("FoundryEndpoint")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("FoundrySessionId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("OutputTokenCount")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("TotalTokenCount")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("UserId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("UpdatedAtUtc")
                        .IsDescending();

                    b.ToTable("ChatConversations", (string)null);
                });

            modelBuilder.Entity("SharePointAgent.Persistence.ChatMessageAttachmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid>("AttachmentFileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AttachmentFileId");

                    b.HasIndex("MessageId", "AttachmentFileId")
                        .IsUnique();

                    b.ToTable("ChatMessageAttachments", (string)null);
                });

            modelBuilder.Entity("SharePointAgent.Persistence.ChatMessageAttachmentFileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("BlobName")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)");

                    b.Property<Guid?>("ChatMessageAttachmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ChunkCount")
                        .HasColumnType("int");

                    b.Property<string>("ContentType")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<long?>("EmbeddingTokenCount")
                        .HasColumnType("bigint");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTimeOffset?>("IndexedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.HasKey("Id");

                    b.HasIndex("ChatMessageAttachmentId")
                        .IsUnique()
                        .HasFilter("[ChatMessageAttachmentId] IS NOT NULL");

                    b.HasIndex("CreatedAtUtc")
                        .IsDescending();

                    b.HasIndex("Status");

                    b.ToTable("ChatMessageAttachmentFiles", (string)null);
                });

            modelBuilder.Entity("SharePointAgent.Persistence.ChatMessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("CitationsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Feedback")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<long>("InputTokenCount")
                        .HasColumnType("bigint");

                    b.Property<string>("ModelId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("OutputTokenCount")
                        .HasColumnType("bigint");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<long>("TotalTokenCount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Feedback")
                        .HasFilter("[Feedback] IS NOT NULL");

                    b.HasIndex("ConversationId", "Sequence")
                        .IsUnique();

                    b.ToTable("ChatMessages", (string)null);
                });

            modelBuilder.Entity("SharePointAgent.Persistence.DeltaStateEntity", b =>
                {
                    b.Property<string>("DriveId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DeltaLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ScanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SweptScanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.HasKey("DriveId");

                    b.ToTable("SharePointDeltaState", (string)null);
                });

            modelBuilder.Entity("SharePointAgent.Persistence.IndexedFileEntity", b =>
                {
                    b.Property<string>("SensitivityLabelId").HasMaxLength(36).HasColumnType("nvarchar(36)");
                    b.Property<string>("SensitivityLabelName").HasMaxLength(255).HasColumnType("nvarchar(255)");
                    b.Property<bool?>("IsLabeled").HasColumnType("bit");
                    b.Property<bool?>("IsEncrypted").HasColumnType("bit");
                    b.Property<DateTimeOffset?>("SensitivityCheckedAtUtc").HasPrecision(7).HasColumnType("datetimeoffset(7)");
                    b.Property<string>("DriveId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ItemId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CTag")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ChunkCount")
                        .HasColumnType("int");

                    b.Property<string>("ETag")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long?>("EmbeddingTokenCount")
                        .HasColumnType("bigint");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("IndexFingerprint")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("IndexedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset?>("LastModifiedUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("MimeType")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ParentPath")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PermissionsHash")
                        .IsRequired()
                        .HasMaxLength(44)
                        .IsUnicode(false)
                        .HasColumnType("char(44)")
                        .IsFixedLength();

                    b.Property<Guid>("ScanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("WebUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("DriveId", "ItemId");

                    b.HasIndex("DriveId", "ScanId");

                    b.ToTable("SharePointIndexedFiles", (string)null);
                });

            modelBuilder.Entity("SharePointAgent.Persistence.WebhookSubscriptionEntity", b =>
                {
                    b.Property<bool>("AutoRenewEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("ClientState")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("GraphSubscriptionId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("LifetimeDays")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NotificationUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.HasKey("Id");

                    b.HasIndex("GraphSubscriptionId")
                        .IsUnique()
                        .HasFilter("[GraphSubscriptionId] IS NOT NULL");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("WebhookSubscriptions", (string)null);
                });

            modelBuilder.Entity("SharePointAgent.Persistence.ChatConversationEntity", b =>
                {
                    b.HasOne("SharePointAgent.Persistence.AgentDefinitionEntity", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("SharePointAgent.Persistence.ChatMessageAttachmentEntity", b =>
                {
                    b.HasOne("SharePointAgent.Persistence.ChatMessageAttachmentFileEntity", "AttachmentFile")
                        .WithMany("MessageAttachments")
                        .HasForeignKey("AttachmentFileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SharePointAgent.Persistence.ChatMessageEntity", "Message")
                        .WithMany("Attachments")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttachmentFile");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("SharePointAgent.Persistence.ChatMessageAttachmentFileEntity", b =>
                {
                    b.HasOne("SharePointAgent.Persistence.ChatMessageAttachmentEntity", "ChatMessageAttachment")
                        .WithOne()
                        .HasForeignKey("SharePointAgent.Persistence.ChatMessageAttachmentFileEntity", "ChatMessageAttachmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ChatMessageAttachment");
                });

            modelBuilder.Entity("SharePointAgent.Persistence.ChatMessageEntity", b =>
                {
                    b.HasOne("SharePointAgent.Persistence.ChatConversationEntity", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("SharePointAgent.Persistence.ChatConversationEntity", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("SharePointAgent.Persistence.ChatMessageAttachmentFileEntity", b =>
                {
                    b.Navigation("MessageAttachments");
                });

            modelBuilder.Entity("SharePointAgent.Persistence.ChatMessageEntity", b =>
                {
                    b.Navigation("Attachments");
                });
#pragma warning restore 612, 618
        }
    }
}
